[Refactor] Remove files moved to request strategy
wireapp/wire-ios-sync-engine pull request #1298
Opened 2020-08-26 14:43 UTC by KaterinaWire

## What's new in this PR?
To be able to convert an update event to a localNotification in Notification engine, we need to have ZMLocalNotification in the Request strategy. In this PR ZMLocalNotification and all required classes are removed.

## Dependencies
wireapp/wire-ios-request-strategy/pull/240

2020-08-26 16:39 UTC, billypchan approved these changes

2020-08-26 19:21 UTC, typfel requested changes

2020-08-26 19:21 UTC, typfel commented on Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
>  @objcMembers public class LocalNotificationDispatcher: NSObject {
The changes in this file can be reverted I guess since it was never moved

2020-08-27 12:47 UTC, KaterinaWire commented on Source/Notifications/Push notifications/LocalNotificationDispatcher.swift
>  @objcMembers public class LocalNotificationDispatcher: NSObject {
Done

2020-09-03 10:06 UTC, merged