[Refactor]  Create APNS token
wireapp/wire-ios-sync-engine pull request #1302
Opened 2020-09-01 17:19 UTC by KaterinaWire

## What's new in this PR?

Check the client iOS and create and send to BE APNS or VoIP token

2020-09-02 14:14 UTC, typfel requested changes

2020-09-02 14:14 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +            NotificationCenter.default.addObserver(forName: SessionManager.registerPushTokenNotificationName, object: nil, queue: nil) { (note) in
Why do we need this notification? We get notified about any new APNS token via the [UIApplicationDelegate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application). UI implementing this delegate but it could forward it to the `SessionManager`.

2020-09-02 14:14 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    public var deviceAPNSToken: Data?
Why do we need to store the `deviceAPNSToken` in the SessionManager? It's persisted in the user client, no?

2020-09-03 14:17 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +                }
Yes, you are right. I did

2020-09-03 14:17 UTC, KaterinaWire commented on Source/SessionManager/SessionManager+Push.swift
> +    public func reRegisterPushToken() {
It's not necessary now. 
Removed.

2020-09-03 14:19 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +            NotificationCenter.default.addObserver(forName: SessionManager.registerPushTokenNotificationName, object: nil, queue: nil) { (note) in
I replaced it with SessionManager method.

2020-09-03 14:19 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +    public var deviceAPNSToken: Data?
Removed it

2020-09-04 06:55 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +            }
Do we first need to delete existing PushKit tokens before registering for APNS?

2020-09-04 06:55 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +            return isSandbox ? "APNS_VOIP_SANDBOX" : "APNS_VOIP"
To avoid repeated OS version checks, I suggest to encode more information in `PushTokenMetaData` and / or elsewhere about what kind of push token we have.

For example:

```swift
// Can be .voip or .standard
let tokenType: PushTokenType
```

You can then use this to simplify code, such as:

```swift
var transportType: String {
    switch tokenType {
        case .standard where isSandbox:
            return "APNS_SANDBOX"
        ...
    }
}
```

2020-09-04 07:00 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +            return isSandbox ? "APNS_VOIP_SANDBOX" : "APNS_VOIP"
Or you could the transport type to the token type:

```swift
enum PushTokenType {
    case standard, voip

    var transportType: String {
        switch self {
            case .standard: return "APNS"
            case .voip: return "APNS_VOIP"
        }
    }
}

...

var transportType: String {
    let result = tokenType.transportType
    return isSandbox ? transportType + "_SANDBOX" ? transportType
}
```

2020-09-04 07:17 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +            }
The API for deleting push token is on swagger as `DELETE push/token/{pid}}` https://staging-nginz-https.zinfra.io/swagger-ui/

I can see two ways forward

1. We register new APNS token immediately, which I think means we'll lose the reference to any previous VoIP token (or can we hold a reference to multiple tokens?). In order to delete any still existing VOIP tokens we would need perform a `GET push/tokens` to get the ID of the existing VoIP token followed by a DELETE request.

2. If we run iOS 13 and we have a VoIP token initially just mark it to be deleted, once the token has been successfully deleted we register for new APNS token.

2020-09-04 07:18 UTC, typfel commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data) {
Why did you mark this as public? Do access it in the tests?

2020-09-04 09:14 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data) {
Yes

2020-09-04 09:15 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +            return isSandbox ? "APNS_VOIP_SANDBOX" : "APNS_VOIP"
Changed

2020-09-07 10:50 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +            }
I'm deleting existing PushKit tokens like this:
1. After launch app we check iOS. If it's 13 (or above) we `registerForRemoteNotifications(). `
2. When we receive a response with a device token, we set it to the self client.
3. We call the `validatePushToken()` method, which compares the push token registered on the backend with the local one. If the client has iOS 13 and a voip token for this client, we send a request to remove the voip token.
The `validatePushToken()` method we also use to reset a push token from the Settings.

2020-09-07 13:26 UTC, typfel requested changes

2020-09-07 13:26 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                let syncMOC = managedObjectContext.zm_sync!
The `managedObjectContext` is already the sync context, all strategies operate on the sync context. Since we can be sure that we already run on the SE context there's also no need to perform `syncMOC.performGroupedBlock()`

2020-09-07 13:26 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    let token = PushToken(deviceToken: voipToken[0].token.hexDecodedData(),
I would suggest to make a PushToken extension here in SE with a convenience initialiser which takes a `PushTokenPayload` as an argument.

**or**

Add a method on `PushTokenPayload` for constructing a `Pushtoken`, like `func createPushToken() -> PushToken`. We use this pattern here https://github.com/wireapp/wire-ios-sync-engine/blob/671d7b052600884b144b79bdb5460774ae268f1d/Source/Synchronization/Strategies/PermissionsDownloadRequestStrategy.swift#L57

2020-09-07 13:26 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    syncMOC.saveOrRollback()
Shouldn't we return early here? Because we wouldn't want to call `resetFlags()`

2020-09-07 13:26 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
We already have this functionality in https://github.com/wireapp/wire-ios-utilities/blob/develop/Source/Public/Data%2BZMSCrypto.swift

2020-09-07 13:47 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
I suggest to make this an initializer for `Data` and move it to WireUtilities. E.g. `Data(fromHexEncodedString: String)`

2020-09-07 13:47 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
It would be fallible too if the string isn't a valid hex string.

2020-09-07 13:47 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
"PushKitToken" is referring to the old PushKit way of getting the (voip) token. 

I think it would be nice if we had a method like:

```swift
    public func setPushToken(_ token: PushToken)
```

Perhaps we could add a token type property to `PushToken`. I think it would make it a bit clearer rather than checking OS versions and code paths.

2020-09-07 13:48 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
Where? I only see the encoding function.

2020-09-07 13:55 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
Oh missed that it decoding hex.

2020-09-07 15:59 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
We have `zmHexEncodedString()` in Data extension that converts data to the hexEncodedString. What if to keep the same pattern and create `zmHexDecodedData()` method in WireUtilities?

2020-09-07 16:25 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                let syncMOC = managedObjectContext.zm_sync!
Removed

2020-09-07 16:26 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    let token = PushToken(deviceToken: voipToken[0].token.hexDecodedData(),
Added `createPushToken()` for the `PushTokenPayload`.

2020-09-07 16:36 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    syncMOC.saveOrRollback()
No, because if we return after `syncMOC.saveOrRollback()` client will have a voipToken as a push token. And when we get a response after the delete request, client.pushToken will be set to nil.
So, we need to continue and set a standard token for userClient. 
`resetFlags()` will be applied for the APNS token.

2020-09-07 20:03 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    syncMOC.saveOrRollback()
But don't we need the voipToken as a push token in order to perform the deletion? I thought it works like this:

1. `markToDownload()` on existing push token, this will trigger a GET request to fetch tokens on BE.
2. Check if backend has VOIP token registered for our client and if so set it as our local PushToken and call markToDelete()
3. Now the PushTokenStrategy will delete the voip token from BE and locally
4. We re-register for a normal a token in order to populate the local PushToken with an APNS token.

Now if replace our local PushToken immediately with a regular token after calling `markToDelete()` how would the `PushTokenStrategy` know which token to delete?

2020-09-07 20:08 UTC, typfel commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +            let voipTokens = clientTokens.filter { $0.transport.contains(PushTokenType.voip.transportType) }
Since you only care about the first VoIP token you could do:

```suggestion
            let voipToken = clientTokens.first(where: { $0.transport.contains(PushTokenType.voip.transportType) })
```

2020-09-07 20:12 UTC, typfel commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
We don't need this to be public in order to access it in Swift tests, If you add `@testable import WireSyncEngine` in  your test file you'll get access to all internal methods.

2020-09-08 06:10 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
I added `setPushToken(_ token: PushToken) `method, but now every time I call this method I need to create a push token object. Is it fine?

2020-09-08 06:14 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
Fixed

2020-09-08 06:25 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    syncMOC.saveOrRollback()
Yes, it works according to this flow.
We have in response method for delete request:
```
 // The token might have changed in the meantime, check if it's still up for deletion
            if let token = client.pushToken, token.isMarkedForDeletion {
                client.pushToken = nil
            }
            return false
```

We remove voip token from BE, but locally we already have another token.

2020-09-08 06:36 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +            self.application.registerForRemoteNotifications()
Yep makes sense.

2020-09-08 06:38 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
You could do both quite easily, just use one implementation and wrap it in the other. Also a quick note, don't forget to test this implementation.

2020-09-08 06:40 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
Yes that's how I imagine it, but how many times do you need to call this method? There should be only two different places, one for PushKit tokens, and one for APNS tokens, right?

2020-09-08 06:49 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> -    let isSandbox: Bool
Is it necessary to move this and `BuildType` to Data Model?

2020-09-08 06:52 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
Another thing you can do is create convenience initializers or static builders for each token type, e.g. `PushToken.createVOIPToken(from: data)` and `PushToken.createAPNSToken(from: data)`.

2020-09-08 07:10 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> -    let isSandbox: Bool
I added `type: PushTokenType` property to the `PushToken` and changed a public initializer:
```
public init(deviceToken: Data, tokenType: PushTokenType, isRegistered: Bool = false) {
        let metadata = PushTokenMetadata.current(for: tokenType)
        self.init(deviceToken: deviceToken,
                  appIdentifier: metadata.appIdentifier,
                  transportType: metadata.transportType,
                  type: tokenType,
                  isRegistered: isRegistered,
                  isMarkedForDeletion: false,
                  isMarkedForDownload: false)
    }
```
So, we don't need to send as a parameter `appIdentifier` and `transportType`.

2020-09-08 07:22 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> -    let isSandbox: Bool
You can define the new initializer in Sync Engine through an extension, that way you don't need to move all that code to Data Model.

You do need to move `PushTokenType`, though I think it now makes more sense to make it a nested type like `PushToken.TokenType`.

2020-09-08 09:26 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +  public func hexDecodedData() -> Data {
Done. I opened a PR in WireUtilities.

2020-09-08 13:49 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> -    let isSandbox: Bool
Done.
Move back `BuildType`.
Opened PR for DataModel.

2020-09-08 13:49 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data, tokenType: PushTokenType) {
Methods `PushToken.createVOIPToken(from: data) `and `PushToken.createAPNSToken(from: data`) are created.

2020-09-08 15:06 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession+Push.swift
> +    public func setPushKitToken(_ data: Data) {
Replaced this method with `setPushToken(_ token: PushToken)` without public access

2020-09-09 17:10 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +                    syncMOC.saveOrRollback()
I've made the changes as we discussed during the call.
1. Delete `voip token` (if client has iOS 13) in the configuration method for user session.
2. Post a notification for the `.deleteToken` response that we should register for remote notifications.

2020-09-10 06:54 UTC, johnxnguyen commented
It would be helpful to have links to the other frameworks that also contain changes.

2020-09-10 07:12 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +            userSession.selfUserClient?.pushToken?.type == .voip {
When decoding the push token from the database, do we account for the fact there may not be a `type` property (since it was recently added?).

2020-09-10 07:12 UTC, johnxnguyen commented on Tests/Source/Integration/LoginFlowTests+PushToken.swift
> +        self.pushRegistry.updatePushToken(deviceToken)
`pushRegistry` here is an instance of `PushRegistryMock` which is a subclass of `PKPushRegistry`. You may need to update tests to account for the new APNS tokens.

2020-09-11 05:35 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +            userSession.selfUserClient?.pushToken?.type == .voip {
https://github.com/wireapp/wire-ios-data-model/pull/1027

2020-09-11 06:05 UTC, KaterinaWire commented on Tests/Source/Integration/LoginFlowTests+PushToken.swift
> +        self.pushRegistry.updatePushToken(deviceToken)
Yes, we don't need to use pushRegistry now. I removed this part.
This test already contain 
```
        let pushToken = PushToken.createAPNSToken(from: deviceToken)
        self.userSession?.setPushToken(pushToken)
```

2020-09-11 06:26 UTC, johnxnguyen approved these changes
Looking fine to me, but I would wait to get more feedback from @typfel .

2020-09-11 06:26 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +    private func registerForVoipPushNotifications() {
Suggestion: `registerForVoipPushNotificationsIfNeeded`

2020-09-11 07:00 UTC, typfel commented on Source/SessionManager/SessionManager+Push.swift
> +        }
You can delete this.

`backgroundUserSessions` also include the active UserSession, even though the names doesn't indicate it.

2020-09-11 07:08 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    private func registerOrMigratePushToken(session userSession: ZMUserSession) {
```suggestion
    private func updateOrMigratePushToken(session userSession: ZMUserSession) {
```

2020-09-11 07:09 UTC, typfel commented
Looks good, just some minor changes suggested.

2020-09-11 07:18 UTC, KaterinaWire commented on Source/SessionManager/SessionManager+Push.swift
> +        }
Done

2020-09-11 07:18 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +    private func registerForVoipPushNotifications() {
Done

2020-09-11 07:20 UTC, typfel approved these changes

2020-09-11 08:23 UTC, merged