Performance] Calculating unread messages
wireapp/wire-ios-sync-engine pull request #1315
Opened 2020-09-30 09:31 UTC by KaterinaWire

## What's new in this PR?

### Issues

We re-calculate the unread message count on every message insert or timestamp change. This is wasteful in a scenario where we receive x messages in the same conversation, we would then calculate the unread count x times when it's enough to do it once after inserting all the messages.
### Solutions

Mark a conversation as needed to update the unread message counter. After creating or updating all messages from update events, update the unread message counter for all conversations.

## Dependencies

wireapp/wire-ios-data-model/pull/1035
https://wearezeta.atlassian.net/browse/ZIOS-13812

TODO: write tests

2020-09-30 09:49 UTC, johnxnguyen requested changes

2020-09-30 09:49 UTC, johnxnguyen commented on Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
> +        conversations.forEach { $0?.calculateLastUnreadMessages() }
I suggest to make put these in a `Set` to remove duplicates, for instance:

```swift
let conversationIds = Set(decryptedUpdateEvents.compactMap(\.conversationUUID)
```

You should also make use of lazy chaining to avoid enumerating the collection several times:

```swift
let conversations = conversationIds.lazy
  .compactMap { ZMConversation.fetch... }
  .filter(\.needsToCalculateUnreadMessages)
  .forEach { $0.calculateLastUnreadMessages() }
```

2020-09-30 10:10 UTC, KaterinaWire commented on Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
> +        conversations.forEach { $0?.calculateLastUnreadMessages() }
Updated

2020-09-30 13:11 UTC, typfel requested changes

2020-09-30 13:11 UTC, typfel commented on Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
> +        let conversationIds = Set(decryptedUpdateEvents.compactMap(\.conversationUUID))
I think it's bit risky to assume that we only touch conversation which referenced by the update events. For example last read update are sent in the self conversation but actually update the lastReadTimestamp is a different conversation.

I think it's safer to do fetch request for all conversation where `needsToCalculateUnreadCount` is `true`

2020-09-30 15:35 UTC, typfel commented on Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
> +    private func calculateUnreadMessagesForConversationsFrom(_ decryptedUpdateEvents: [ZMUpdateEvent]) {
`decryptedUpdateEvents` argument can be removed.

2020-09-30 15:37 UTC, typfel commented on Source/Synchronization/ZMSyncStrategy+EventProcessing.swift
> +    private func calculateUnreadMessagesForConversationsFrom(_ decryptedUpdateEvents: [ZMUpdateEvent]) {
I think we should move this method to data model, It could be class method on `ZMConversation`.

2020-09-30 16:26 UTC, typfel approved these changes

2020-10-02 11:59 UTC, KaterinaWire commented
@zenkins release minor

2020-10-02 12:00 UTC, merged