[Fix] Do not check the file extension
wireapp/wire-ios-sync-engine pull request #1318
Opened 2020-10-06 15:30 UTC by KaterinaWire

## What's new in this PR?

### Issues
When you sent a backup file through the email, the Gmail app changes the file extension.(xxx.ios_wbu to xxx.ios-wbu).

### Causes
There is the Gmail app issue.
https://support.google.com/mail/thread/15716995?hl=en

### Solutions
Do not check the file extension and accept both file extensions.

## Dependencies

wireapp/wire-ios/pull/4634
https://github.com/wireapp/wire-ios/issues/4609

2020-10-06 16:05 UTC, marcomaddy1982 approved these changes

2020-10-07 07:03 UTC, johnxnguyen requested changes
I think we should keep the validation of the file extension, just extend it to now accept the two different versions.

2020-10-07 09:24 UTC, KaterinaWire commented
> I think we should keep the validation of the file extension, just extend it to now accept the two different versions.

But we never use this verification, because on the UI side we only allow certain file types to be selected.

2020-10-07 09:46 UTC, johnxnguyen commented
> But we never use this verification, because on the UI side we only allow certain file types to be selected.

@KaterinaWire indeed, but this is an assumption that verification happens outside of the framework. The sync engine doesn't know about the UI and therefore shouldn't make any assumptions about how the framework is used. It seems like a trivial thing because we know that only the UI uses the sync engine, but even small assumptions like this can lead to nasty bugs.

2020-10-07 09:57 UTC, KaterinaWire commented
> > But we never use this verification, because on the UI side we only allow certain file types to be selected.
> 
> @KaterinaWire indeed, but this is an assumption that verification happens outside of the framework. The sync engine doesn't know about the UI and therefore shouldn't make any assumptions about how the framework is used. It seems like a trivial thing because we know that only the UI uses the sync engine, but even small assumptions like this can lead to nasty bugs.

Yes, it makes sense. The verification is restored and modified.

2020-10-07 11:35 UTC, johnxnguyen requested changes
It would be good to add a test for the new behavior.

2020-10-08 07:47 UTC, KaterinaWire commented
> It would be good to add a test for the new behavior.

@johnxnguyen Added test

2020-10-08 09:05 UTC, johnxnguyen approved these changes

2020-10-08 09:26 UTC, KaterinaWire commented
@zenkins release patch

2020-10-08 09:28 UTC, merged