[Refactor]:[WIP]: AppStateCalculator Tests
wireapp/wire-ios-sync-engine pull request #1330
Opened 2020-10-27 12:13 UTC by marcomaddy1982

## What's new in this PR?

This PR is still in WIP, I will write more detail once it will be completed

2020-10-27 13:16 UTC, typfel requested changes

2020-10-27 13:16 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerRegisterDatabaseLocked(isDatabaseLocked: Bool)
This approach looks like it should work. I would change the names though to still reflect that the session manager operates on user sessions. Maybe it even make sense to not distinguish between the the database locked/unlock case.

```suggestion
    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
```

2020-10-27 13:16 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +                self?.databaseEncryptionObserverToken = nil
We have no active user session here, therefore `databaseEncryptionObserverToken` should already be `nil`.

2020-10-27 13:16 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +        databaseEncryptionObserverToken = nil
I would couple nilling there `databaseEncryptionObserverToken ` to when we set the `activeUserSession` to `nil`. Maybe introduce a `tearDownActiveUserSession()` method?

2020-10-27 13:16 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func registerDatabaseLocked(userSession: ZMUserSession) {
```suggestion
    func registerDatabaseLockedObserver(userSession: ZMUserSession) {
```

2020-10-27 13:16 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +        databaseEncryptionObserverToken = nil
or

We register the database lock observer for all users sessions by doing it inside `registerObservers(account: Account, session: ZMUserSession)`. The observer is then coupled to the life cycle of users session. Then you would need to add a `guard` before calling `delegate.sessionManagerRegisterDatabaseLocked()`, which checks that it was the `activeUserSession` was locked/unlocked.

2020-10-27 15:49 UTC, typfel requested changes

2020-10-27 15:49 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +            self?.delegate?.sessionManagerChangedActiveUserSession(isDatabaseLocked: session.isDatabaseLocked)
Now you need to guard that  `session == activeUserSession`

2020-10-27 15:49 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerWillChangeActiveUserSession(userSession: ZMUserSession?)
Why is `ZMUserSession` optional?

2020-10-27 15:49 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
It's tricky to find good names for this situation for these two states that the active user session can be in. Maybe something like this? We **change** the active user session when we switch between the account and we **update** the current active session when it's either authenticated or when the database is locked/unlocked.

```suggestion
    func sessionManagerDidChangeActiveUserSession(_ userSession: ZMUserSession)
    func sessionManagerDidUpdateActiveUserSession(isDatabaseLocked: Bool)
```

2020-10-27 15:49 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
ping @johnxnguyen

2020-10-27 15:59 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerWillChangeActiveUserSession(userSession: ZMUserSession?)
Yep probably we don't need it.

2020-10-27 16:11 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
`sessionManagerDidUpdateActiveUserSession` is a little misleading because the session manager isn't doing anything to the active user session, it's just passing on information that the active user session database became locked / unlocked.

Perhaps something like

```swift
func activeUserSessionDatabaseLockDidChange(isLocked: Bool)
```

2020-10-27 16:14 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
yep, makes sense. Thanks a lot!!!

2020-10-27 16:16 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
I guess we added "sessionManager" at the beginning to be aligned with all the other methods of the delegate (see also `SessionManagerDelegate`) and because basically this call back is fired by the `SessionManager`.

2020-10-27 16:17 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
Anyway I will use you hint cause it is definitely more descriptive.

2020-10-27 16:22 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
Even if the session manager is just delegating information I would still write it from the session managers perspective, this makes the delegate methods consistent.

`sessionManagerDidObserveDatabaseLockChange(isLocked: Bool)`
`sessionManagerDidReportDatabaseLockChange(isLocked: Bool)`
`sessionManagerDidReportDatabaseLockChangeForActiveUserSession(isLocked: Bool)`

2020-10-27 16:26 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +    func sessionManagerChangedActiveUserSession(isDatabaseLocked: Bool)
ok at this point I go for 

`sessionManagerDidReportDatabaseLockChange(isLocked: Bool)`

2020-10-28 15:09 UTC, typfel requested changes

2020-10-28 15:09 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +            self?.delegate?.sessionManagerDidReportDatabaseLockChange(isLocked: session.isDatabaseLocked)
You are still missing the check that `session == activeUserSession`.

2020-10-28 15:09 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +                userSession == self?.activeUserSession
This is redundant since we only call `checkIfLoggedIn()` on the `activeUserSession`

2020-10-28 15:09 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +        delegate?.sessionManagerDidChangeActiveUserSession(userSession: userSession)
This doesn't fit the description of the function. I would move it out again.

2020-10-29 11:43 UTC, typfel approved these changes
Tests are failing though

2020-10-30 07:05 UTC, merged