Fix/x code 12 request optional
wireapp/wire-ios-sync-engine pull request #1335
Opened 2020-11-04 14:21 UTC by billypchan

## What's new in this PR?

Follow up of https://github.com/wireapp/wire-ios-data-model/pull/1055

2020-11-04 14:45 UTC, typfel requested changes

2020-11-04 14:45 UTC, typfel commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +        }
Why not do a `guard let` on the  `request` instead and return early?

2020-11-04 14:45 UTC, typfel commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +        }
`guard let`on `request` here as well?

2020-11-04 14:45 UTC, typfel commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
>          let request = ZMUser.sortedFetchRequest(with: predicate)
Perhaps it better to update the nullability annotation on `sortedFetchRequest(with:)`? Looking at the implementation it doesn't seem like it can return `nil` https://github.com/wireapp/wire-ios-data-model/blob/305143fc5ef693be3dfeef28440f991aecf1d1de/Source/Model/ZMManagedObject.m#L260

2020-11-04 15:09 UTC, billypchan commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +        }
The 2 lines below:
```
        ZMUser.selfUser(in: context).needsToBeUpdatedFromBackend = true
        context.enqueueDelayedSave()
```

are still needed in case `users` is nil?

2020-11-05 14:18 UTC, KaterinaWire commented on Source/UserSession/Search/SearchResult+AddressBook.swift
> +        guard let users = managedObjectContext.executeFetchRequestOrAssert(fetchRequest) as? [ZMUser] else {
Shouldn't there be `managedObjectContext.fetchOrAssert(request:...)` ?

2020-11-05 14:21 UTC, KaterinaWire commented on Source/UserSession/Search/SearchTask.swift
> +        conversations = searchContext.fetchOrAssert(request: fetchRequest) as? [ZMConversation] ?? []
Do we need a declaration of `conversations` on a separate line?

2020-11-05 14:23 UTC, KaterinaWire commented on Tests/Source/Synchronization/Transcoders/ConversationStatusStrategyTests.swift
> +            let result = self.syncMOC.executeFetchRequestOrAssert(request! ) as! [NSManagedObject]
Shouldn't there be `self.syncMOC.fetchOrAssert(request:...) `?

2020-11-05 14:26 UTC, billypchan commented
@KaterinaWire there are still 25 occurances  of `executeFetchRequestOrAssert`, I would open another PR to convert them and this PR only fixed the issues related to data model update.

2020-11-05 16:07 UTC, KaterinaWire commented
> @KaterinaWire there are still 25 occurances of `executeFetchRequestOrAssert`, I would open another PR to convert them and this PR only fixed the issues related to data model update.

Ok

2020-11-05 16:09 UTC, KaterinaWire approved these changes

2020-11-05 16:10 UTC, typfel approved these changes

2020-11-11 11:14 UTC, billypchan commented
@zenkins release major

2020-11-11 11:15 UTC, merged