[Feature]: EAR and export backup
wireapp/wire-ios-sync-engine pull request #1342
Opened 2020-11-16 09:45 UTC by marcomaddy1982

## What's new in this PR?

as we mentioned in the data-model [PR](https://github.com/wireapp/wire-ios-data-model/pull/1068) for the `EAR and export backup` before to put the backup into an encrypted container using the password the user previously entered first we have to decrypt the EAR if enabled. In order to complete this operation we need to retrieve the  `EncryptionKeys`.

## Dependencies

data-model: https://github.com/wireapp/wire-ios-data-model/pull/1068

2020-11-16 14:03 UTC, typfel requested changes

2020-11-16 14:03 UTC, typfel commented on Source/SessionManager/SessionManager+Backup.swift
> +        if activeUserSession?.storeProvider.contextDirectory.uiContext.encryptMessagesAtRest ?? false {
```suggestion
        if activeUserSession?.encryptMessagesAtRest {
```

2020-11-16 14:03 UTC, typfel commented on Source/SessionManager/SessionManager+Backup.swift
> +        if activeUserSession?.storeProvider.contextDirectory.uiContext.encryptMessagesAtRest ?? false {
Let's add wrap the `activeUserSession` in the guard? There's no point in continuing without a user session.

2020-11-16 14:03 UTC, typfel commented on Source/SessionManager/SessionManager+Backup.swift
> +enum EARBackupError: LocalizedError {
I'd prefer to add another case to the existing `BackupError`

2020-11-16 14:03 UTC, typfel commented on Source/SessionManager/SessionManager+Backup.swift
> +    public func backupActiveAccount(password: String, completion: @escaping BackupResultClosure) throws {
Why is this method throwing now?

2020-11-16 14:13 UTC, typfel commented on Source/SessionManager/SessionManager+Backup.swift
> +            encryptionKeys: encryptionKeys,
```suggestion
            encryptionKeys: activeUserSession.managedObjectContext.encryptionKeys,
```

Could also access the `encryptionKeys` like this and then you don't need deal with the error here.

2020-11-16 15:30 UTC, typfel approved these changes

2020-11-17 07:36 UTC, johnxnguyen approved these changes

2020-11-17 14:28 UTC, typfel commented on Source/UserSession/ZMUserSession+EncryptionAtRest.swift
> +        }
This should be deleted.

2020-11-17 14:29 UTC, marcomaddy1982 commented on Source/UserSession/ZMUserSession+EncryptionAtRest.swift
> +        }
Exactly, that was my doubt.

2020-11-17 15:04 UTC, merged