[Refactor]: Expand the SessionManagerDelegate
wireapp/wire-ios-sync-engine pull request #1348
Opened 2020-11-30 15:48 UTC by marcomaddy1982

## What's new in this PR?

the method of the `SessionManagerDelegate` (in the new version it is not there anymore)

```swift
func sessionManagerDidFailToLogin(account: Account?,
                                      from selectedAccount: Account?,
                                      error: Error)
```

 is currently called in situations which is unexpected, this means that we have been forced to add filtering logic in the `UI` to disregard these situations.

### Solutions

Introduce more callback to the `UI` (in order also the make more descriptive and clear what is happening in the `SE`) and passing the `Error` in the callBacks when necessary

## Dependencies

JIRA: [SQCORE-215](https://wearezeta.atlassian.net/browse/SQCORE-215)

2020-12-02 06:37 UTC, typfel requested changes
AFAIK the issue with `sessionManagerDidFailToLogin()` is that it's also called for accounts which are not the active user session or the user session we are trying to login into. That's why we had to add the filtering logic in the UI code.

Splitting `sessionManagerDidFailToLogin()` up into several methods doesn't solve this issue though, they will still be called for none active accounts.

An example of such case is when a user has two accounts A and B. A is the active account at the moment but the user session for B is also loaded since a push notification has been received previously. If the cookie for account B gets deletes it will trigger `authenticationInvalidated()`. This causes `sessionManagerDidFailToLogin()` to be called but we don't want to show the logged out screen since we are displaying the logged in state for account A.

2020-12-02 09:10 UTC, marcomaddy1982 commented
> AFAIK the issue with `sessionManagerDidFailToLogin()` is that it's also called for accounts which are not the active user session or the user session we are trying to login into. That's why we had to add the filtering logic in the UI code.
> 
> Splitting `sessionManagerDidFailToLogin()` up into several methods doesn't solve this issue though, they will still be called for none active accounts.
> 
> An example of such case is when a user has two accounts A and B. A is the active account at the moment but the user session for B is also loaded since a push notification has been received previously. If the cookie for account B gets deletes it will trigger `authenticationInvalidated()`. This causes `sessionManagerDidFailToLogin()` to be called but we don't want to show the logged out screen since we are displaying the logged in state for account A.

Ok, if I understood correctly what we should do is 

```swift
guard account == accountManager.selectedAccount else { return }
```

before the `sessionManagerDidFailToLogin` is called.
Anyway if you are agree I would keep the separation the separation of the `sessionManagerDidFailToLogin` in several methods.

2020-12-02 10:54 UTC, typfel commented
> Anyway if you are agree I would keep the separation the separation of the `sessionManagerDidFailToLogin` in several methods.

But what purpose this separation achieve? In the UI you perform the same operation in all cases. I would not make the API more complex if we don't have to.

> Ok, if I understood correctly what we should do is
>
> ```
> guard account == accountManager.selectedAccount else { return }
> ```

Yes, we need to do something like that and you also need verify if we need such checks in the other call sites.

2020-12-03 08:02 UTC, marcomaddy1982 commented
> > Anyway if you are agree I would keep the separation the separation of the `sessionManagerDidFailToLogin` in several methods.
> 
> But what purpose this separation achieve? In the UI you perform the same operation in all cases. I would not make the API more complex if we don't have to.
> 
> > Ok, if I understood correctly what we should do is
> > ```
> > guard account == accountManager.selectedAccount else { return }
> > ```
> 
> Yes, we need to do something like that and you also need verify if we need such checks in the other call sites.

> But what purpose this separation achieve? In the UI you perform the same operation in all cases. I would not make the API more complex if we don't have to.

ok, no problem. I will revert to the old version that's not a problem. 

> Yes, we need to do something like that and you also need verify if we need such checks in the other call sites.
I already had a look yesterday but of course I can check it again.

2020-12-03 08:37 UTC, marcomaddy1982 commented
@typfel your suggestion are applied, please have a look if there is some scenario that I have missed or not considered.

2020-12-04 06:52 UTC, typfel requested changes

2020-12-04 06:52 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +            guard account == accountManager.selectedAccount else { return }
I think we need to do a similar check in `clientRegistrationDidFail()`

2020-12-04 07:40 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +        delegate?.sessionManagerDidFailToLogin(error: error)
@typfel I'm responding here to the other comment you made. It is already done in the `clientRegistrationDidFail()`. It is bit unclear the diff GitHub is showing for this change.

2020-12-04 08:38 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +        delegate?.sessionManagerDidFailToLogin(error: error)
Ah I missed that 👍

2020-12-04 08:40 UTC, typfel requested changes

2020-12-04 08:40 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +                guard account == accountManager.selectedAccount else { return }
Here we should not have this check because the selected account is updated afterwards in the `completion` block.  I think we assume that we always want to inform the UI in this scenario.

2020-12-04 08:40 UTC, typfel commented on Source/SessionManager/SessionManager.swift
> +        delegate?.sessionManagerDidFailToLogin(error: error)
I guess gitub showed me an outdated diff.

2020-12-04 08:58 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +                guard account == accountManager.selectedAccount else { return }
Done

2020-12-04 08:59 UTC, typfel approved these changes

2020-12-04 16:17 UTC, KaterinaWire commented on Source/SessionManager/SessionManager.swift
> +                        self?.delegate?.sessionManagerDidFailToLogin(error: nil)
Why `error` is nil here?

2020-12-07 08:32 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +                        self?.delegate?.sessionManagerDidFailToLogin(error: nil)
We don't need there to pass the error and we won't show any alert to the user

2020-12-07 10:21 UTC, KaterinaWire approved these changes

2020-12-07 10:25 UTC, marcomaddy1982 commented
@zenkins major release

2020-12-07 10:31 UTC, merged