[Refactor] Move featureConfigRequestStrategy from the RequestStrategy
wireapp/wire-ios-sync-engine pull request #1366
Opened 2020-12-18 07:25 UTC by KaterinaWire

## What's new in this PR?

Move `featureConfigRequestStrategy` from the RequestStrategy  and trigger it during slow sync.

2020-12-18 07:42 UTC, johnxnguyen requested changes
Don't forget to test generating requests during the sync phase.

2020-12-18 07:42 UTC, johnxnguyen commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +                         syncStatus: SyncStatus) {
```suggestion
    public init(withManagedObjectContext managedObjectContext: NSManagedObjectContext,
                applicationStatus: ApplicationStatus,
                syncStatus: SyncStatus) {
```

2020-12-18 07:42 UTC, johnxnguyen commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +        guard syncStatus.currentSyncPhase == .fetchingFeatureConfigs else { return nil }
Right now this strategy will only produce a request during slow sync. 

What changed in this method? Did we have a guard at all?

2020-12-18 07:42 UTC, johnxnguyen commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +        }
This method is for processing the response of a single config, but the slow sync is really about fetching **all** configs. So we don't want to finish the sync phase here.

2020-12-18 07:42 UTC, johnxnguyen commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +            return
We should probably finish the sync phase here too because otherwise we risk to block the slow sync. Do we do a similar thing in other strategies?

2020-12-18 14:14 UTC, KaterinaWire commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +        }
Removed

2020-12-18 14:15 UTC, KaterinaWire commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +            return
Put `syncStatus.finishCurrentSyncPhase(phase: .fetchingFeatureConfigs)` into the `defer` block

2020-12-18 16:06 UTC, KaterinaWire commented on Source/Synchronization/Strategies/FeatureConfigRequestStrategy.swift
> +        guard syncStatus.currentSyncPhase == .fetchingFeatureConfigs else { return nil }
Updated

2020-12-21 12:32 UTC, johnxnguyen approved these changes

2020-12-28 08:31 UTC, billypchan approved these changes

2020-12-28 08:32 UTC, billypchan requested changes
test failed.

2021-01-06 16:43 UTC, closed without merging