[Refactoring]: SQCORE-363 Unify Login/Registration API
wireapp/wire-ios-sync-engine pull request #1388
Opened 2021-02-02 10:42 UTC by marcomaddy1982

## What's new in this PR?

### Issues

As we already described in the [RFC](https://wearezeta.atlassian.net/wiki/spaces/IOS/pages/159646019/Simplify+API+for+Login+Registration) we would have liked to unify the `Login and Registration API`. Unfortunately this is not possible to achieve as described in the RFC. The initial idea was create a unique `LoginStatus` object in the `SE` representing all the phases when an user logs in:

- Sign In
- Restore Backup 
- Client Registration

and then create a `LoginStatusDelegate` that informs the `UI` of any changes in the phases.

Anyway, before to explain the reasons why this was not possible we should first describe the current implementation: 
In the `SE` the login status representation was split in two objects:

- `ZMAuthenticationStatus` for the  Sign In and Restore Backup steps. The  `ZMAuthenticationStatus` is strictly related to the `UnauthenticatedSession`.
- `ZMClientRegistrationStatus` for the Client Registration step. The `ZMClientRegistrationStatus` is strictly related to the `UserSession`.

Moreover, they will inform the `AuthenticationCoordinator` (`UI`) and the `SessionManager` (SE) about the changes of their phases through two different `NotificationObserver`:

- `ZMAuthenticationStatus` through the `PreLoginNotificatinObsever`
- `ZMClientRegistrationStatus` through the `PostLoginNotificatinObsever` 

Since the `ZMAuthenticationStatus` is strictly related to the `UnauthenticatedSession` and the `ZMClientRegistrationStatus` to the `UserSession` it is pretty clear that  it is not possible unify them in a unique object or create a relation between them. 

In addition, the `PreLoginNotificatinObsever` and the `PostLoginNotificatinObsever` aren't used just to inform the `UI` of the changes respectively of the `ZMAuthenticationStatus` and `ZMClientRegistrationStatus` but also to inform of the login process changes the `SessinManager` in the `SE`. 
This means that it is not possible having just one delegate object going from the `ZMAuthenticationStatus`/`ZMClientRegistrationStatus` to the `UI` but we need a "more-steps" delegation that use the `SessinManager` as a proxy between the `ZMAuthenticationStatus`/`ZMClientRegistrationStatus` and the `UI`.  Here the delegation steps we introduced in the solution:

- `ZMAuthenticationStatus`-> `ZMAuthenticationStatusDelegate`->`SessionManager`->`LoginDelegate` ->`AuthenticationCoordinator`

- `ZMClientRegistrationStatus`-> `ZMClientRegistrationStatusDelegate` -> `UserSession`-> `UserClientDelegate`-> `SessionManager`->`LoginDelegate`->`AuthenticationCoordinator`

in addition to this the `PostLoginNotificatinObsever` was used to dispatch to `SE` objects like other events not directly related to the login process:

- logout
- account deletion

These events are now covered respectively by the `LogoutDelegate` and the `DeleteAccountObserver.

2021-02-04 14:26 UTC, typfel requested changes

2021-02-04 14:26 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didAuthenticationInvalidate:(NSError *)error;
I know it called something similar in the `PostLoginAuthenticationNotification` but it's confusing. It think a more descriptive name would be:

`didDeleteSelfUserClient()`

2021-02-04 14:26 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrationUserClient:(NSError *)error;
```suggestion
- (void)didFailToRegisterSelfUserClient:(NSError *)error;
```

2021-02-04 14:26 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
>  - (void)didRegisterUserClient:(UserClient *)userClient;
```suggestion
- (void)didRegisterSelfUserClient:(UserClient *)userClient;
```

2021-02-04 14:26 UTC, typfel commented on Source/SessionManager/UserCientDelegate.swift
> +//
Filename has a typo: `UserCientDelegate.swift ` > `UserClientDelegate.swift`

2021-02-04 14:26 UTC, typfel commented on Source/SessionManager/UserCientDelegate.swift
> +public protocol UserClientDelegate: NSObjectProtocol {
I actually think we should move it to the `UserSession` and call it `UserSessionSelfUserClientDelegate`

2021-02-04 14:26 UTC, typfel commented on Source/SessionManager/LogoutDelegate.swift
> +public protocol LogoutDelegate: NSObjectProtocol {
I think we should move it to the UserSession and call it `UserSessionLogoutDelegate `

2021-02-04 14:26 UTC, typfel commented on Source/SessionManager/UserCientDelegate.swift
> +    func authenticationInvalidated(_ error: NSError, accountId : UUID)
I'm thinking it might make sense to remove this method and move it to the `LogoutDelegate`?

2021-02-04 14:26 UTC, typfel commented on Source/UnauthenticatedSession/UnauthenticatedSession.swift
> +    public var authenticationStatus: ZMAuthenticationStatus
I think we should keep the `ZMAuthenticationStatus` private, we could inject the delegate instead.

2021-02-04 17:24 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +            session.authenticationStatus.notifyAuthenticationDidFail(error)
I guess you are right!!! Thanks.

2021-02-04 17:25 UTC, marcomaddy1982 commented on Source/UserSession/DeleteAccountNotification.swift
> +@objc public protocol DeleteAccountObserver: NSObjectProtocol {
I'm agree about all you naming suggestion. I just comment here :-)

2021-02-04 17:34 UTC, marcomaddy1982 commented on Source/SessionManager/SessionManager.swift
> +        loginDelegate?.authenticationDidFail(error)
Actually I was not sure too. Let's remove it.

2021-02-04 17:54 UTC, marcomaddy1982 commented on Source/SessionManager/UserCientDelegate.swift
> +//
This can be removed not if we move it in the UserSession. Anyway thanks for pointing it out

2021-02-04 18:02 UTC, marcomaddy1982 commented on Source/SessionManager/UserCientDelegate.swift
> +    func authenticationInvalidated(_ error: NSError, accountId : UUID)
Good point!! I think you are absolutely right!!!

2021-02-04 18:04 UTC, marcomaddy1982 commented on Source/SessionManager/UserCientDelegate.swift
> +    func authenticationInvalidated(_ error: NSError, accountId : UUID)
Good point!!! You are right!!!

2021-02-05 07:35 UTC, marcomaddy1982 commented
@typfel I guess I've addressed all your comment.

2021-02-05 07:54 UTC, typfel requested changes
Quite a few comments got lost when files changed.

2021-02-05 07:54 UTC, typfel commented on Source/Utility/NSManagedObjectContext+GenericAsyncQueue.swift
> +public protocol GenericAsyncQueue {
This is not used anywhere so it can be removed or re-introduced later when it's used.

2021-02-05 07:54 UTC, typfel commented on Source/UserSession/ZMUserSession.swift
> +    var logoutDelegate: UserSessionLogoutDelegate?
Commented got lost due to other changes:

These protocols could be part of the UserSessionDelegate like this:

typealias UserSessionDelegate = UserSessionEncryptionAtRestDelegate & UserClientDelegate & UserClientDelegate
The reason why is because the SessionManager will be the delegate for all these protocols so it's easier to inject it only once and we don't need to keep adding parameters for every new user session delegate.

2021-02-05 07:54 UTC, typfel commented on Source/UserSession/AccountDeletedObserver.swift
> +@objcMembers public class AccountDeletedNotification : NSObject {
This can be simplified by using inheriting from the  `SelfPostingNotification`. See `WireCallCenterV3+Notifications.swift` for examples

2021-02-05 07:54 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
>  - (void)didRegisterUserClient:(UserClient *)userClient;
Still not resolved

2021-02-05 07:54 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrationUserClient:(NSError *)error;
Still not resolved

2021-02-05 07:54 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didAuthenticationInvalidate:(NSError *)error;
Still not resolved

2021-02-05 09:11 UTC, marcomaddy1982 commented on Source/Utility/NSManagedObjectContext+GenericAsyncQueue.swift
> +public protocol GenericAsyncQueue {
This is used in the `ZMUserSession+Debugging.swift` line `251`.

2021-02-05 09:29 UTC, typfel commented on Source/Utility/NSManagedObjectContext+GenericAsyncQueue.swift
> +public protocol GenericAsyncQueue {
I don't see any changes to `ZMUserSession+Debugging.swift` in this PR. Did you forget to push it?

2021-02-05 13:11 UTC, marcomaddy1982 commented on Source/Utility/NSManagedObjectContext+GenericAsyncQueue.swift
> +public protocol GenericAsyncQueue {
No it was already there, the `GenericAsyncQueue` was in the `PostLoginNotification` class, I just moved out from there and created an ad hoc file for it. It is not something I've created from scratch.

2021-02-08 07:23 UTC, typfel requested changes
Just some typos and other minor stuff.

2021-02-08 07:23 UTC, typfel commented on Source/Calling/WireCallCenterV3+Notifications.swift
> +                let context = note.context,
Extra space

2021-02-08 07:23 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrerSelfUserClient:(NSError *)error;
```suggestion
- (void)didFailToRegisterSelfUserClient:(NSError *)error;
```

2021-02-08 07:23 UTC, typfel commented on Source/UserSession/ZMUserSession+Authentication.swift
> +            let accoutId = ZMUser.selfUser(inUserSession: self).remoteIdentifier,
Still not fixed.

2021-02-08 07:23 UTC, typfel commented on Source/UnauthenticatedSession/ZMAuthenticationStatus.h
> +- (void)resetLoginAndRegistrationStatus;
I guess this can stay internal now?

2021-02-08 08:28 UTC, marcomaddy1982 commented on Source/UnauthenticatedSession/ZMAuthenticationStatus.h
> +- (void)resetLoginAndRegistrationStatus;
Yes, right thanks!

2021-02-08 08:39 UTC, marcomaddy1982 commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrerSelfUserClient:(NSError *)error;
@typfel sorry i forgot to mention last time: if I rename it as you suggested on the swift implementation I will have:

```swift
public func didFail(toRegisterSelfUserClient error: Error!)
```

that's why I choose the name without "to".

2021-02-08 08:43 UTC, marcomaddy1982 commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrerSelfUserClient:(NSError *)error;
@typfel anyway there is also the typo to fix!!

2021-02-11 06:59 UTC, johnxnguyen commented on Source/SessionManager/SessionManager.swift
> +    public var loginDelegate: LoginDelegate?
Should this be `weak`?

2021-02-11 06:59 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession.swift
> +            }
Maybe add this as a private extension on the context to avoid duplication:

```swift
private extension NSManagedObjectContext {
    var selfUserId: UUID? {
        ZMUser.selfUser(in: self).remoteIdentifier
    }
}
```

2021-02-11 09:38 UTC, johnxnguyen approved these changes

2021-02-11 16:24 UTC, typfel requested changes
Just one more wording issue

2021-02-11 16:24 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegisterSelfUserClient:(NSError *)error;
```suggestion
- (void)didFailToRegisterSelfUserClient:(NSError *)error;
```

2021-02-11 16:28 UTC, typfel commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrerSelfUserClient:(NSError *)error;
You can define the swift name with an annotation like this: `NS_SWIFT_NAME(didFailToRegisterSelfUserClient(:))`

2021-02-11 16:50 UTC, marcomaddy1982 commented on Source/Synchronization/ZMSyncStateDelegate.h
> +- (void)didFailRegistrerSelfUserClient:(NSError *)error;
Done

2021-02-11 16:51 UTC, typfel approved these changes

2021-02-11 17:34 UTC, merged