[Feature] Notify user to remove from conversation due to legal hold policy conflict
wireapp/wire-ios-sync-engine pull request #1437
Opened 2021-05-19 12:54 UTC by KaterinaWire

## What's new in this PR?

Needs releases with:

- [ ] 

## Notes

2021-05-24 02:25 UTC, KaterinaWire commented on Resources/Base.lproj/Push.strings
> +"push.notification.member.leave.self.legalhold-policy-conflict" = "You were removed from a group, because there are users with Legal Hold";
There's an agreement with Eva to show a simplified `"You were removed"` notification

2021-05-24 06:52 UTC, johnxnguyen requested changes

2021-05-24 06:52 UTC, johnxnguyen commented on Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
> +        let reasonKey = reason?.stringValue
Is this a localization key? I think you should switch On the `reason` instead because the compiler will complain if the value changes, but it won't complain if the string value changes, which would break the implementation.

2021-05-25 06:09 UTC, KaterinaWire commented on Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
> +        let reasonKey = reason?.stringValue
I removed this key

2021-05-25 06:10 UTC, KaterinaWire commented
> A snapshot test would be great if you can add one.

@johnxnguyen I don't think we have snapshots in SE

2021-05-25 06:16 UTC, johnxnguyen commented
> @johnxnguyen I don't think we have snapshots in SE

@KaterinaWire ahah... yes indeed, wrong project!

2021-05-25 06:17 UTC, johnxnguyen approved these changes

2021-05-25 09:28 UTC, merged