[Feature] Add ZMHotFixPatch for updating client capabilities
wireapp/wire-ios-sync-engine pull request #1440
Opened 2021-05-22 14:01 UTC by KaterinaWire

## What's new in this PR?

All updated clients that can support the new BE end-points, related to legal hold should send `"capabilities": [ "legalhold-implicit-consent"]` to BE. 
There is a new HotFix patch that checks the current version and sends capabilities to BE.

Needs releases with:

- [ wireapp/wire-ios-data-model/pull/1159 ]

2021-05-22 14:20 UTC, johnxnguyen commented on Source/Synchronization/Strategies/UserClientRequestFactory.swift
> +    }
This would be a suitable place to use `guard let`.

2021-05-22 14:20 UTC, johnxnguyen commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +    }
Considering https://github.com/wireapp/wire-ios-data-model/pull/1159#discussion_r637409392, you would only need to call

```swift
UserClient.triggerSelfClientCapabilityUpdate()
```

2021-05-22 14:48 UTC, KaterinaWire commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +    }
Fixed

2021-05-22 14:48 UTC, KaterinaWire commented on Source/Synchronization/Strategies/UserClientRequestFactory.swift
> +    }
Done

2021-05-22 15:02 UTC, johnxnguyen commented on Source/Synchronization/Strategies/UserClientRequestFactory.swift
> +            return nil
You could throw the client not registered error here, if you want.

2021-05-22 15:02 UTC, johnxnguyen commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +    }
As I understand it, you neither need to check if the self client exists nor enqueue a save because this is the responsibility of `triggerSelfClientCapabilityUpdate`

2021-05-22 15:59 UTC, typfel commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +    }
Or you remove the save inside the data model method.

2021-05-22 16:23 UTC, KaterinaWire commented on Source/Synchronization/Strategies/UserClientRequestFactory.swift
> +            return nil
Ah... I misunderstood you
Fixed it:
```
guard let remoteIdentifier = client.remoteIdentifier else {
            throw UserClientRequestError.clientNotRegistered
}
```

2021-05-22 16:24 UTC, KaterinaWire commented on Source/Synchronization/ZMHotFixDirectory+Swift.swift
> +    }
Removed here since both are in DM

2021-05-22 17:06 UTC, typfel approved these changes

2021-05-24 06:46 UTC, johnxnguyen requested changes

2021-05-24 06:46 UTC, johnxnguyen commented on Tests/Source/SessionManager/SessionManagerTests.swift
> +//final class SessionManagerTests: IntegrationTest {
Don't forget to uncomment this.

2021-05-24 18:47 UTC, KaterinaWire commented on Tests/Source/SessionManager/SessionManagerTests.swift
> +//final class SessionManagerTests: IntegrationTest {
I commented these test because they fail on Jenkins on the develop branch. I'll try to figure out the reason, but for now, to be able to merge PRs, I've commented them.

2021-05-25 11:52 UTC, johnxnguyen approved these changes

2021-05-25 12:18 UTC, merged