[Feature] Add an endpoint to join a conversation
wireapp/wire-ios-sync-engine pull request #1450
Opened 2021-06-08 10:50 UTC by KaterinaWire

## What's new in this PR?

Add an endpoint that we can use to join the conversation with the code and key from the deep link.

## Notes
https://wearezeta.atlassian.net/browse/SQSERVICES-501

2021-06-08 14:12 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +        }))
Since we're returning the error in the result type, what do you think about adding the log statement higher up in the call stack?

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +                "from" :connectedUser.remoteIdentifier.transportString()] as ZMTransportData
```suggestion
                "from": connectedUser.remoteIdentifier.transportString()] as ZMTransportData
```

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let connectedUser = user(for: self.selfUser)!
What is the significance of the `connectedUser`? My understanding is that if the self user is joining the conversation, then the update event will be from themself, and the affected users ("users" and "users_ids") will be the self users. At least, this is what I think is the case when the self users leaves a conversation on their own will.

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        XCTAssertTrue(conversation!.localParticipants.contains(connectedUser))
Shouldn't this assert that the self users is a local participant?

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +                            code: "test-code",
I suppose these test values don't affect the test result whatsoever? If true, then perhaps it's worth mentioning in a comment.

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let conversationJoiningFailed = expectation(description: "Failed to join the conversation")
There is a missing wait for this expectation.

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +    func testThatTheUserIsAParticipantInTheConversation() {
Perhaps `testConversationJoin_WhenTheSelfUsersIsAlreadyAParticipant`

2021-06-08 14:12 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let userIsParticipant = expectation(description: "The user was already a participant in the conversation")
There is a missing wait for this expectation.

2021-06-08 14:34 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +    public static func join(uri: String? = nil,
Yes, we won't use this parameter now. But it's possible to send uri parameter and, maybe, in the future we will use it.

2021-06-08 15:01 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +    case unknown, tooManyMembers, noConversationCode
According to the documentation, it means the code is invalid. I will rename it to `invalidCode`.

2021-06-08 15:09 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let conversationJoiningFailed = expectation(description: "Failed to join the conversation")
Why?

2021-06-08 15:10 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let userIsParticipant = expectation(description: "The user was already a participant in the conversation")
Why?

2021-06-08 17:09 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +    func testThatTheUserIsAParticipantInTheConversation() {
Done

2021-06-08 17:11 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let connectedUser = user(for: self.selfUser)!
Yes, you are right. The method `user(for:...)` converts `MockUser` to `ZMUser`. I renamed this name to `selfUser_zmUser`

2021-06-08 17:12 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        XCTAssertTrue(conversation!.localParticipants.contains(connectedUser))
connectedUser is selfUser, but ZMUser type. I renamed it

2021-06-08 17:16 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +                            code: "test-code",
Done

2021-06-08 17:59 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
Added a switch for the` response.httpStatus`

2021-06-08 18:00 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
Yes, 204 means the user is already a participant of the conversation. Added comment

2021-06-08 18:00 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
> What is the significance of 204? Is it the case when the user is already a participant of the conversation? If so, this is not clear from the code, so I would at least add a comment.

Yes, 204 means the user is already a participant of the conversation. Added comment

2021-06-08 18:01 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
> You could improve readability by using a switch for the outer if blocks:
> 
> ```swift
> switch response.httpStatus {
> case 200:
>   ...
> case 204:
>   ...
> default:
>   ...
> }
> ```

Added a switch for the response.httpStatus

2021-06-08 18:03 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
> When handling a 200 status, if we don't find a payload then we still complete with a success. What does this mean?

It's not correct, the payload should be. If there is no payload, it's a BE error.

2021-06-08 18:05 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        }))
> Since we're returning the error in the result type, what do you think about adding the log statement higher up in the call stack?

I didn't understand where and why you are suggesting to move the log statement.

2021-06-09 06:05 UTC, typfel requested changes

2021-06-09 06:05 UTC, typfel commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let userIsParticipant = expectation(description: "The user was already a participant in the conversation")
See previous explanation.

2021-06-09 06:05 UTC, typfel commented on Tests/Source/Integration/ConversationTests+Join.swift
> +    func testConversationJoin_WhenTheSelfUserJoinsAConversation_OnSuccessfulResponse() {
```suggestion
    func testThatTheSelfUserJoinsAConversation_OnSuccessfulResponse() {
```

2021-06-09 06:05 UTC, typfel commented on Tests/Source/Integration/ConversationTests+Join.swift
> +    func testConversationJoin_WhenTheSelfUserDoesNotJoinAConversation_OnFailureResponse() {
```suggestion
    func testThatTheSelfUserDoesNotJoinAConversation_OnFailureResponse() {
```

2021-06-09 06:05 UTC, typfel commented on Tests/Source/Integration/ConversationTests+Join.swift
> +    func testConversationJoin_WhenTheSelfUsersIsAlreadyAParticipant() {
```suggestion
    func testThatAnErrorIsNotReported_WhenTheSelfUsersIsAlreadyAParticipant() {
```

2021-06-09 06:14 UTC, johnxnguyen requested changes

2021-06-09 06:14 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +    public static func join(uri: String? = nil,
So would you only use either the uri or the code/key pair? If yes, then it"s better to have two methods each with obvious usage instead of one.

2021-06-09 06:14 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let conversationJoiningFailed = expectation(description: "Failed to join the conversation")
If you don't wait for the exception then the test will end after the last line, meaning the completion handler that uses the wait may not be invoked.

You need to call something like: 

```swift
XCTAssertTrue(waitForExpectations([conversationJoiningFailed], timeout: 0.5))
```

2021-06-09 06:14 UTC, johnxnguyen commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let userIsParticipant = expectation(description: "The user was already a participant in the conversation")
See the previous comment.

2021-06-09 06:14 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                }
Now the completion handler is not being called when there doesn't exist a payload. I suggest to make this all one guard statement and return an error when it fails:

```swift
guard
  let payload = ...,
  let event = ...,
  let syncMoce = ...
else {
  completion(.failure(...))
  return
}
```

2021-06-09 06:14 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                }
Or you might want to use two separate guards so you can return different errors.

2021-06-09 10:44 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +    public static func join(uri: String? = nil,
Removed `uri` from parameters

2021-06-09 11:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                }
Fixed

2021-06-09 11:14 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let userIsParticipant = expectation(description: "The user was already a participant in the conversation")
Done

2021-06-09 11:14 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        let conversationJoiningFailed = expectation(description: "Failed to join the conversation")
Done

2021-06-09 11:27 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        }
The original idea was to have it in `wire-ios-mocktransport`, but in the response payload we have a `conversationID` and I need to have this id in the SE to check that the conversation didn't exist before the join request and does exist after request.

2021-06-09 11:47 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                syncMOC.performGroupedBlock {
Will this happen synchronously? If not, then it might be possible that the completion is called prematurely.

2021-06-10 06:22 UTC, typfel commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        }
You can't create a MockConversation and retrieve its ID and do the same check?

2021-06-10 06:27 UTC, typfel commented on Source/Data Model/Conversation+Join.swift
> +                syncMOC.performGroupedBlock {
It will happens asynchronously so the completion handler will be called before response had been processed. I can't answer if this is an issue I also noticed that the other conversation actions have the same behaviour/problem.

2021-06-10 09:33 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +    public static func join(uri: String? = nil,
> So would you only use either the uri or the code/key pair? If yes, then it"s better to have two methods each with obvious usage instead of one.

According to the documentation, only `uri` parameter is optional. I also tried in Swagger to send only one parameter 
```
{
  "uri": "https://wire-webapp-staging.zinfra.io/join/?key=tuc7wPATadG3Ny3sdmZO&code=GN1hm5S6aKcpvhhZa_IQ"
}
```
and received an error
```
{
  "code": 400,
  "message": "Error in $: key \"key\" not found",
  "label": "invalid-payload"
}
```
It looks like we can't use 2 options, so there is no need to create two methods.

2021-06-13 23:03 UTC, KaterinaWire commented on Tests/Source/Integration/ConversationTests+Join.swift
> +        }
Added wireapp/wire-ios-mocktransport/pull/174

2021-06-14 06:19 UTC, typfel requested changes

2021-06-14 06:19 UTC, typfel commented on Source/Data Model/Conversation+Join.swift
> +                            completion: @escaping (VoidResult, ZMConversation?) -> Void) {
Having a `VoidResult` and an optional `ZMConversation` defeats the purpose of the result parameter. Make it a Result which returns a conversation: `Result<ZMConversation>`.

2021-06-14 06:19 UTC, typfel commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +class DeepLinkURLActionProcessorTests: IntegrationTest {
This was a unit tests but now you are turning it into a integration test. Because you are passing in the `userSession`, why is this necessary?

2021-06-14 06:19 UTC, typfel commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +    var userSession: ZMUserSession
Why are you adding the userSession here? You don't seem to use it for anything.

2021-06-14 06:19 UTC, typfel commented on Source/UserSession/ZMUserSession.swift
> +            DeepLinkURLActionProcessor(userSession: self),
This will create a retain cycle since the UserSession is the owner of the `DeepLinkURLActionProcessor`

2021-06-14 06:22 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                        return
The completion handler isn't being called here.

2021-06-14 08:30 UTC, johnxnguyen commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +class DeepLinkURLActionProcessorTests: IntegrationTest {
All these tests are unit tests because they are only asserting the interfacing with the presentation delegate, so I don't think we should be inheriting `IntegrationTest` here.

2021-06-14 08:51 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                     contextProvider: ContextProvider?,
Is there a reason why these are optional? Perhaps you can unwrap them in the calling method?

2021-06-14 08:51 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                      let viewMOC = contextProvider?.viewContext,
As per the previous comment, I think you should unwrap these earlier because they're not directly related to the response, meaning that if you can't unwrap any of these, then you will make the request to the backend for no reason.

2021-06-14 08:51 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                        completion(.success, conversation)
You're passing a conversation associated with the sync context to the view context, this will cause an exception when that conversation is used.

2021-06-14 08:51 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +    static func join(key: String,
I see three contexts used in this method: `moc`, `syncMOC` and `uiMOC`. You need the sync moc for event processing, but perhaps you don't need `moc` (is it already the sync moc? Should it be?). 

Also, I'm not sure that this method should be assuming that the completion should be run on the ui thread, but rather leaving the caller to decide. You could just wait for the block on the sync context to finish, then call the completion on whatever thread the method was called on.

2021-06-14 21:03 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                            completion: @escaping (VoidResult, ZMConversation?) -> Void) {
Replaced

2021-06-14 21:03 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                        return
Fixed

2021-06-15 06:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                     contextProvider: ContextProvider?,
Fixed

2021-06-15 06:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                      let viewMOC = contextProvider?.viewContext,
Fixed

2021-06-15 06:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +    static func join(key: String,
Fixed

2021-06-15 06:16 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +    var userSession: ZMUserSession
I don't need `userSession`, but I need `transportSession`, `eventProcessor`, `contextProvider`. I need it to setup a join conversation request. 
Instead of passing `userSession`, I replaced it with `transportSession`, `eventProcessor`, `contextProvider`.

2021-06-15 06:17 UTC, KaterinaWire commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +class DeepLinkURLActionProcessorTests: IntegrationTest {
Replaced back

2021-06-15 06:19 UTC, KaterinaWire commented on Source/UserSession/ZMUserSession.swift
> +            DeepLinkURLActionProcessor(userSession: self),
Yeah...
I replaced it as explained in the previous comment

2021-06-15 06:43 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                    completion(.success(conversation))
If this method is called on the main thread and `moc` is the sync context, then we will still get a core data threading violation here since `conversation` must only be used within the sync context. Instead of passing the managed object to the completion handler, you could pass the conversation id. The completion handler would then need to fetch the conversation from the view context.

2021-06-15 06:50 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                    completion(.success(conversation))
Ooops my mistake, this is being called wIthin the moc block. Still, you'll need to get this conversation on the view context though, so it may still be easier to pass in the conversation id.

2021-06-15 10:11 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                    completion(.success(conversation))
Yes, you are right. I also understood it when run the app on the simulator. 
I changed this part, the event is handled in `syncMOC`, and the conversation fetching and the completion are in the `uiMOC`.
```
syncMOC.performGroupedBlock {
 eventProcessor.storeAndProcessUpdateEvents([event], ignoreBuffer: true)  
            
        uiMOC.performGroupedBlock {                      
          guard let conversationId = UUID(uuidString: conversationString),                      
                  let conversation = ZMConversation(remoteID: conversationId, createIfNeeded: false, in: uiMOC) else {   
                                                 return completion(.failure(ConversationJoinError.unknown))          
                                }                        completion(.success(conversation))            
   }
```

2021-06-15 10:14 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                        completion(.success, conversation)
I left a comment on this here: https://github.com/wireapp/wire-ios-sync-engine/pull/1450#discussion_r651648229

2021-06-15 10:18 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +    var userSession: ZMUserSession
I removed this part since it's not really a part of this PR. You will find these changes in another PR: wireapp/wire-ios-sync-engine/pull/1453
Instead of `userSession` I use `transportSession`, `eventProcessor`, `contextProvider`

2021-06-15 12:20 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                    completion(.success(conversation))
It would be good to add in the doc comment that if the completion is a success, it is run in the main thread.

2021-06-15 12:26 UTC, johnxnguyen approved these changes

2021-06-15 12:26 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +        default: return nil
You could improve this by making the init not fallible and defaulting to the `unknown` case.

2021-06-15 12:26 UTC, johnxnguyen commented on Source/Data Model/Conversation+Join.swift
> +                        }
Formatting nitpick: I don't have a strong opinion exactly how to format, but I think it should at least be consistent. The previous guard in this method places the `else` on a new line.

2021-06-15 14:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +        default: return nil
Done

2021-06-15 14:13 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                    completion(.success(conversation))
Added

2021-06-15 14:35 UTC, typfel approved these changes

2021-06-15 20:51 UTC, merged