[Feature] Process the url action to join the conversation
wireapp/wire-ios-sync-engine pull request #1453
Opened 2021-06-13 22:45 UTC by KaterinaWire

## What's new in this PR?

Make a request and handle the result for the url action to join the conversation.

2021-06-14 08:35 UTC, johnxnguyen commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +                        delegate?.showConversation(conversation, at: nil)
Passing in the conversation as a `Result<ZMConversation>` will make this safer and clearer to read. For instance, it means that we would never have the success case without a reference to the conversation, making the awkward   guard here unnecessary.

2021-06-14 15:20 UTC, typfel requested changes

2021-06-14 15:20 UTC, typfel commented on Source/Data Model/Conversation+Join.swift
> +                syncMOC.performGroupedBlockAndWait {
Why does this need to be a `blockAndWait`?

2021-06-15 06:41 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +                        delegate?.showConversation(conversation, at: nil)
Fixed

2021-06-15 10:00 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> -            delegate?.shouldPerformAction(urlAction) { shouldJoin in
We don't need it, because shouldPerformAction is triggered by the UI project (Also checked on the simulator).

2021-06-15 10:02 UTC, KaterinaWire commented on Source/Data Model/Conversation+Join.swift
> +                syncMOC.performGroupedBlockAndWait {
We don't need it, I removed it.

2021-06-15 12:30 UTC, johnxnguyen reviewed
Are there tests that the delegate methods are called?

2021-06-15 12:30 UTC, johnxnguyen commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +            let uiMOC = contextProvider.viewContext
It's nice to be consistent with naming, so I'd suggest `viewContext`.

2021-06-15 12:30 UTC, johnxnguyen commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +            let uiMOC = contextProvider.viewContext
Suggestion: `viewContext`

2021-06-15 14:35 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +            let uiMOC = contextProvider.viewContext
Done

2021-06-15 14:36 UTC, KaterinaWire commented on Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
> +            let uiMOC = contextProvider.viewContext
Done

2021-06-15 14:36 UTC, KaterinaWire commented
> Are there tests that the delegate methods are called?

Tests were added

2021-06-15 14:37 UTC, typfel approved these changes

2021-06-16 06:47 UTC, johnxnguyen commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
To align with the test name, shouldn't we assert with `shouldPerformActionCalls`?

2021-06-16 06:47 UTC, johnxnguyen commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
Also, do we want to assert that it asks to show the conversation?

2021-06-16 10:36 UTC, KaterinaWire commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
We can't ask to assert `showConversationCalls`, because there is a `mockUpdateEventProcessor` that doesn't process events and there's no conversation as a result. I just added one assertion `XCTAssertEqual(mockUpdateEventProcessor.processedEvents.count, 1)`  to make sure we are accepting the event.

2021-06-16 10:44 UTC, KaterinaWire commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
> To align with the test name, shouldn't we assert with `shouldPerformActionCalls`?

I chose this name to be consistent with test names in this file. These test only check the processing url actions. If you have suggestions to rename it, we can apply it.
As for `shouldPerformActionCalls`, we have a test class `SessionManagerTests_URLActions`, that checks `shouldPerformActionCalls`. But this class uses the connectService url action as an example.

2021-06-16 12:18 UTC, johnxnguyen commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
`testThatItCompletesTheJoinConversationAction_WhenCodeIsValid` and `testThatItReportsTheJoinConversationActionAsFailed_WhenCodeIsInvalid`

2021-06-18 04:38 UTC, KaterinaWire commented on Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
> +        XCTAssertEqual(presentationDelegate.completedURLActionCalls.first, action)
Renamed

2021-06-18 11:11 UTC, johnxnguyen approved these changes

2021-06-18 11:55 UTC, merged