[Feature] Integrate AVS selective video endpoint
wireapp/wire-ios-sync-engine pull request #1465
Opened 2021-06-30 13:22 UTC by David-Henner

## What's new in this PR?

AVS selective video allows to specify which video streams should be loaded and made available by avs.
This is helpful in the context of large conference calls, where we only want to receive video streams for participants that are visible on screen.

### Changes

- Added support for the avs selective video endpoint. 
- Restructured AVS support files. Each struct gets its own file, which helps with searching and declutters the files.
- Updated tests

2021-06-30 14:07 UTC, KaterinaWire commented on Source/Calling/AVS/AVSClient.swift
> +
Just a small note, in `CodingKeys` enum you didn't make an empty line before `case`.

2021-06-30 14:12 UTC, KaterinaWire commented on Source/Calling/AVS/AVSWrapper.swift
> +    public func requestVideoStreams(_ videoStreams: AVSVideoStreams, conversationId: UUID) {
According to the comment, we should provide a clients list, but we don't have such a parameter. Am I wrong?

2021-06-30 14:19 UTC, David-Henner commented on Source/Calling/AVS/AVSWrapper.swift
> +    public func requestVideoStreams(_ videoStreams: AVSVideoStreams, conversationId: UUID) {
Good catch! At first the parameter was a clients list but I've changed it and forgot to update the comment. I'll update.

2021-07-01 06:14 UTC, typfel requested changes

2021-07-01 06:14 UTC, typfel commented on Source/Calling/AVS/JSONStringEncodable.swift
> +    }
You are creating `JSONEncoder` instance every time you are encoding to JSON here. We have similar use case here https://github.com/wireapp/wire-ios-request-strategy/blob/f0458055a360b978bc4f00489dc12ad180f0c12f/Sources/Payloads/Payload%2BDecoding.swift#L77

You could adapt the same strategy here and do something like:
```
func jsonString(encoder: JSONEncoder = .init()) -> String? {
    guard let data = try? encoder.encode(self) else { return nil }
    return String(data: data, encoding: .utf8)
}
```

You could then create the JSONEncoder and store it in the `AVSWrapper` and supply it when doing the encoding. In the tests you could rely on the default encoder for convenience.

2021-07-01 06:14 UTC, typfel commented on Tests/Source/Calling/AVSVideoStreamsTest.swift
> +    func testThat_JsonStringValue_IsConformTo_avsAPI() {
```suggestion
    func testThatJSONStringValue_ConformToAVSAPI() {
```

2021-07-05 05:48 UTC, KaterinaWire commented on Source/Calling/AVS/AVSWrapper.swift
> +    /// Requests AVS to load at list of video streams
Requests AVS to load a list of video streams

2021-07-05 05:49 UTC, KaterinaWire approved these changes

2021-07-06 08:55 UTC, typfel approved these changes

2021-08-04 18:03 UTC, David-Henner commented
@zenkins release major

2021-08-04 18:04 UTC, merged