chore: Restore self-deleting messages SQSERVICES-1059
wireapp/wire-ios-sync-engine pull request #1586
Opened 2021-11-23 15:12 UTC by KaterinaWire

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1059" title="SQSERVICES-1059" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQSERVICES-1059</a>  Restore self-deleting messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Restore self-deleting messages

Needs releases with:

- [ wireapp/wire-ios-data-model/pull/1293 ] 
- [ wireapp/wire-ios-request-strategy/pull/432 ]

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-11-23 15:35 UTC, johnxnguyen approved these changes

2021-11-23 16:37 UTC, typfel commented on Source/Synchronization/ZMHotFix.m
> +    NSString * currentVersionString = @"402";
402.0.0?

2021-11-23 16:37 UTC, typfel requested changes
Copy the full version from version.xconfig?

2021-11-23 16:48 UTC, KaterinaWire commented on Source/Synchronization/ZMHotFix.m
> +    NSString * currentVersionString = @"402";
Yes, fixed.
`402.0.0` will be the new version.

2021-11-23 16:49 UTC, KaterinaWire commented
> Copy the full version from version.xconfig?

I've changed the version in `version.xconfig`

2021-11-23 17:03 UTC, typfel approved these changes

2021-11-24 09:44 UTC, KaterinaWire commented
release major

2021-11-24 10:25 UTC, KaterinaWire commented
release major

2021-11-24 10:42 UTC, billypchan commented
release major

2021-11-24 10:46 UTC, billypchan commented
release major

2021-11-24 10:48 UTC, billypchan commented
release major

2021-11-24 10:49 UTC, merged