feat: Delete legacy push token SQSERVICES-1502
wireapp/wire-ios-sync-engine pull request #1727
Opened 2022-04-28 15:43 UTC by KaterinaWire

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1502" title="SQSERVICES-1502" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />SQSERVICES-1502</a>  [iOS] App crashes in the background on upgrading to the new test flight version 3.100
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Adjust a `PushTokenStrategy` to be able remove legacy push token and post new one.

Needs releases with:

- [ wireapp/wire-ios-data-model/pull/1361 ] 

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-04-29 11:07 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +        return ZMUpstreamRequest(keys: [Keys.UserClientPushTokenKey, Keys.UserClientLegacyPushTokenKey], transportRequest: request, userInfo: [Keys.RequestTypeKey: requestType.rawValue])
Maybe we only need to include the key relevant to the request?

2022-04-29 14:05 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +        return ZMUpstreamRequest(keys: [Keys.UserClientPushTokenKey, Keys.UserClientLegacyPushTokenKey], transportRequest: request, userInfo: [Keys.RequestTypeKey: requestType.rawValue])
Done

2022-05-02 07:42 UTC, johnxnguyen requested changes
Some tests would be good to assert:

- deleting push token marks the push token and moves it to a legacy property
- generating requests to delete the legacy token
- processing the response to delete the legacy token

2022-05-02 07:42 UTC, johnxnguyen commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +
I suggest add a comment why we return `true`, something like: "Return true to indicate more requests are needed because we still need to register the new push token."

2022-05-02 07:42 UTC, johnxnguyen commented on Source/UserSession/ZMUserSession+Push.swift
> +            selfClient.pushToken = nil
To make it clearer, I think we should distinguish between deleting the legacy token and the non-legacy token. We could for instance have parameter to express this:

```swift
func deletePushKitToken(isLegacy: Bool = false) {
    let syncMOC = managedObjectContext.zm_sync!

    syncMOC.performGroupedBlock {
        guard let selfClient = ZMUser.selfUser(in: syncMOC).selfClient() else { return }
        guard let pushToken = selfClient.pushToken else { return }

        if isLegacy {
            // Move the token to another property to free up space for
            // a new non-legacy token.
            selfClient.legacyPushToken = pushToken.markToDelete()
            selfClient.pushToken = nil
        } else {
            selfClient.pushToken = pushToken.markToDelete()
        }

        syncMOC.saveOrRollback()
    }
}
```

2022-05-03 07:27 UTC, KaterinaWire commented on Source/Synchronization/Strategies/PushTokenStrategy.swift
> +
Done

2022-05-04 12:55 UTC, johnxnguyen approved these changes

2022-05-05 06:55 UTC, KaterinaWire commented
release minor

2022-05-05 06:56 UTC, zenkins commented
Hello, @KaterinaWire! Merging PR for command **release minor** for PR #**1727**. Will create a **minor** release after merged.
Next version is 422.1.0.

2022-05-05 06:56 UTC, merged